# Generated by Django 2.1.2 on 2018-10-03 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TEST', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='period',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='period',
            name='locomotive',
        ),
        migrations.DeleteModel(
            name='Period',
        ),
    ]
